version: '2'
services:
    manager:
        build:
          dockerfile: manager.dockerfile
          context: .
    executer:
        build:
          dockerfile: executer.dockerfile
          context: .
    submitter:
        build:
          dockerfile: submitter.dockerfile
          context: .
